name: SonarQube analysis

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]
  workflow_dispatch:

permissions:
  pull-requests: read 

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: |
            ~/.nuget/packages
            ~/.local/share/NuGet/v3-cache
            ~/.dotnet/tools
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj','**/packages.lock.json','global.json','nuget.config') }}-v1
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test (generate OpenCover)
        run: |
          dotnet test ./Azure.API.Tests/Azure.API.Tests.csproj -c Release --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=TestResults/coverage.opencover.xml

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin Sonar Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          dotnet-sonarscanner begin /k:"MikolajKocik_WorkPulse" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/coverage.opencover.xml" \
            /d:sonar.exclusions="**/bin/**,**/obj/**"

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: End Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
